version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    container_name: rabbitmq
    ports:
      - '15672:15672'
      - '15692:15692'
      - '25676:25676'
      - '35672:5672'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - ada-network
networks:
  ada-network:
    external: true